add Chlorine page
msse-chem-280-2023/periodic-table pull request #103
Opened 2023-07-31 23:39 UTC by jyyu830

- add element symbol
- add atomic number 
- add a short description about Chlorine

2023-07-31 23:49 UTC, SpencerUyematsu requested changes
Add facts about chlorine

2023-07-31 23:56 UTC, jihyunc2 approved these changes
Yes I agree. Chlorine is used as disinfectants!

2023-07-31 23:57 UTC, SpencerUyematsu approved these changes

2023-07-31 23:59 UTC, merged

2023-08-01 16:13 UTC, jyyu830 commented
closes #51